language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install cmake -y

before_script:
  - mkdir build
  - cd build
  - cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON

script:
  - make
  - make check